aliases:
  steps: &steps
    - checkout
    - setup_remote_docker

    - run: docker pull "${DOCKER_HUB_REPO}/mail:${VERSION}-relay" || true
    - run: docker build -t "${DOCKER_HUB_REPO}/mail:${VERSION}-relay" --cache-from="${DOCKER_HUB_REPO}/mail:${VERSION}-relay" .

    - run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - run: docker push "${DOCKER_HUB_REPO}/mail:${VERSION}-relay"

version: 2
jobs:
  build-relay:
    docker:
      - image: circleci/python:3.7.2-stretch
    environment:
      VERSION: "1.0"
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - build-relay:
          context: docker-hub
